version: 2
updates:
  # Updates for main branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - ricardozanini
      - fjtirado
    target-branch: "main"

  # Updates for 4.x branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - ricardozanini
      - fjtirado
    target-branch: "4.x"

  # Updates for 5.x branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - ricardozanini
      - fjtirado
    target-branch: "5.x"
